# Generated by Django 3.0.6 on 2020-06-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stalkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ip', models.CharField(default='Unkown', max_length=60)),
                ('useragent', models.CharField(default='Unknown', max_length=100)),
                ('datatime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='stalkersIn',
        ),
    ]
