# Generated by Django 3.0.6 on 2020-06-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0003_auto_20200605_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stalkers',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
