# Generated by Django 3.0.6 on 2020-06-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0004_auto_20200605_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalkers',
            name='ip',
            field=models.CharField(default='Unknown', editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='stalkers',
            name='useragent',
            field=models.CharField(default='Unknown', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='stalkers',
            name='username',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
