# Generated by Django 3.0.6 on 2020-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0005_auto_20200605_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalkers',
            name='ip',
            field=models.CharField(default='Unknown', max_length=60),
        ),
        migrations.AlterField(
            model_name='stalkers',
            name='useragent',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='stalkers',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
