# Generated by Django 3.0.6 on 2020-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0006_auto_20200605_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalView', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
